### PR TITLE
Add authorization

### PR DESCRIPTION
**Pull request by Gopxfs**
# Summary 📒 
For this milestone, I:
- Added 'CanCanCan' gem.
- Added `role` column to the users' table.
- Added authorization conditions to:
  - If the user is an admin/author of the post, it is possible to delete the post.
  - If the user is an admin/author of the comment, it is possible to delete the comment.

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi team, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏
- [ ] There is an error in `PostsController#create` which does not allow a user to create a post. Kindly see the error below and fix it.
post


## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Gopxfs** [comment]
> ## Required Changes ♻️
> > "Change is inevitable. Change is constant. -Benjamin Disraeli"
> 
> ## Hi team,
> ### You have been doing a tremendous job so far 👌
> ## To Highlight 🎉
> PR has a title and summary. ✔️ Git flow is followed. ✔️
> 
> ## To Improve 🙏
> * [ ]  There is an error in `PostsController#create` which does not allow a user to create a post. Kindly see the error below and fix it.
>   post
> 
> ## Optional suggestions
> _Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._
> 
> ## Happy coding!👏👏👏
> #### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> #### Please remember to tag me in your question so I can receive the notification.
> **_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

Hello @SajjadAhmad14 , I'm being able to create new posts normally. Could you specify when this is happening?

**Comment by SajjadAhmad14** [comment]
Hi, 

So error shows that there is a syntax error on line 37. If I remove ` locals: { post: }, status: 422` and only render new action there is no error and post is created,

**Comment by Gopxfs** [comment]
@SajjadAhmad14 I'm not being able to reproduce the error on my computer. I asked for a second opinion to see if the problem is on my device

**Comment by Gopxfs** [comment]
I dropped the database and everything is still working:
image

Did you pull the correct branch?

**Review by ahmetbozaci — COMMENTED** [review]
Hello @Gopxfs  👋,

_This is an additional review as a result of the second opinion request._
- I can create posts, comments, and like without error. 
image
- I believe this error comes from the ruby version difference. In the old ruby version you have to put something after the `:`  `{ post: }`  but rubocop deletes if it saw {post: post}. In ruby 3.1.2 it is not a problem.

**Kindly resubmit your project next code reviewer will approve it.**


Keep rocking 🚀! // can be customized

**Comment by Gopxfs** [comment]
> Hello @Gopxfs 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> * I can create posts, comments, and like without error.
>   image
> * I believe this error comes from the ruby version difference. In the old ruby version you have to put something after the `:`  `{ post: }`  but rubocop deletes if it saw {post: post}. In ruby 3.1.2 it is not a problem.
> 
> **Kindly resubmit your project next code reviewer will approve it.**
> 
> Keep rocking 🚀! // can be customized

I appreciate it.

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @Gopxfs, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
